### PR TITLE
[WIP] SassC support

### PR DESCRIPTION
**Pull request by bolandrm**
This is very much WIP.  Comments on the approach are welcome.

This depends on sprockets master (https://github.com/rails/sprockets/pull/148)

### CODE REVIEW

**Comment by jeremy** [comment]
:+1:

**Comment by guilleiguaran** [comment]
@bolandrm I like the approach you're following in this. 

We can add sassc gem commented on rails Gemfile and then the users can un-comment it to enable as alternative to default sass.

**Comment by guilleiguaran** [comment]
I've added `:sassc` as compressor in https://github.com/rails/sprockets/commit/dc78af8c72a68c7f4446510157023dd11df66dac, so it can be switched in https://github.com/rails/sass-rails/blob/master/lib/sass/rails/railtie.rb#L80

**Comment by bolandrm** [comment]
Thanks @guilleiguaran.  Testing this in a rails app.  Working out some load path issues.

**Comment by camelmasa** [comment]
I hope it will be merge  :+1: @bolandrm Will you continue this PR :question:  Or, we should use https://github.com/sass/sassc-rails :question:

**Comment by Fudoshiki** [comment]
sassc-rails works fine, but would like sassc in rails by default

**Comment by schneems** [comment]
I had some issues with windows and sassc. https://github.com/rails/sprockets/blob/master/test/shared_sass_tests.rb#L117 I tried to fix it, even bought a windows machine. I got hung up on the compilation toolchain and had to move to something else.

I'm interested in getting sassc support in sass-rails, would love to help move this along if possible.

**Comment by MikeRogers0** [comment]
I think sassc had a patch to fix the windows install problems ( https://github.com/sass/sassc/pull/206 ) :D

I'm not sure the state of this branch, but I'd love to see this pushed out to all the gems still using sass :)

**Comment by guilleiguaran** [comment]
See https://github.com/rails/sass-rails/pull/424

**Pull request closed without merging**
